apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  storageClassName: manual # <--- Añade esto
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/config/vaultwarden/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: vaultwarden
spec:
  storageClassName: manual # <--- Añade esto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi